openapi: 3.0.1
info:
   title: Debug Plugin
   description: A plugin that allows ChatGPT to access and modify files on your computer for debugging purposes.
   version: 'v1'
servers:
   -  url: http://localhost:5003
paths:
  /files/{filename}:
    get:
      operationId: getFile
      summary: Get the contents of a file
      parameters:
      - in: path
        name: filename
        schema:
            type: string
        required: true
        description: The name of the file.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getFileResponse'
    post:
      operationId: modifyFile
      summary: Modify a file
      parameters:
      - in: path
        name: filename
        schema:
            type: string
        required: true
        description: The name of the file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modifyFileRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    getFileResponse:
      type: object
      properties:
        content:
          type: string
          description: The content of the file.
    modifyFileRequest:
      type: object
      required:
      - content
      properties:
        content:
          type: string
          description: The new content of the file.
          required: true
