openapi: 3.0.1
info:
   title: Debug Plugin
   description: A plugin that allows ChatGPT to access and modify files on your computer for debugging purposes.
   version: 'v1'
servers:
   -  url: http://localhost:5003
paths:
  /execute:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executeCommandRequest'
      responses:
        '200':
          description: Command executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/executeCommandResponse'
        '400':
          description: Error occurred while executing command
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/executeCommandErrorResponse'
  /run_script:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runScriptRequest'
      responses:
        '200':
          description: Script ran successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runScriptResponse'
        '400':
          description: Error occurred while running script
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runScriptErrorResponse'
  /files/{filename}:
    get:
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: File content retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getFileResponse'
        '404':
          description: File not found
    post:
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modifyFileRequest'
      responses:
        '200':
          description: File modified successfully
  /initialize:
    post:
      operationId: initialize_plugin
      requestBody:
        required: false
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/initializePluginResponse'
        '400':
          description: Error during initialization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/initializePluginResponse'
components:
  schemas:
    executeCommandRequest:
      type: object
      required:
      - command
      properties:
        command:
          type: string
          description: The command to execute.
        env_name:
          type: string
          description: The name of the environment (optional).
    executeCommandResponse:
      type: object
      properties:
        output:
          type: string
          description: The output of the command.
    executeCommandErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message.
        output:
          type: string
          description: The output of the command before it failed.
    runScriptRequest:
      type: object
      required:
      - env_name
      - script_path
      properties:
        env_name:
          type: string
          description: The name of the environment.
        script_path:
          type: string
          description: The path to the Python script.
    runScriptResponse:
      type: object
      properties:
        output:
          type: string
          description: The output of the script.
    runScriptErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message.
        output:
          type: string
          description: The output of the script before it failed.
    getFileResponse:
      type: object
      properties:
        content:
          type: string
          description: The content of the file.
    modifyFileRequest:
      type: object
      required:
      - content
      properties:
        content:
          type: string
          description: The new content of the file.
    modifyFileResponse:
      type: object
      properties:
        message:
          type: string
          description: The status of the file modification.
    initializePluginResponse:
      type: object
      properties:
        message:
          type: string
          description: The status of the initialization.