openapi: 3.0.1
info:
   title: Debug Plugin
   description: A plugin that allows ChatGPT to access and modify files on your computer for debugging purposes.
   version: 'v1'
servers:
   -  url: http://localhost:5003
paths:
  /files:
    get:
      operationId: getFile
      summary: Get the contents of a file
      parameters:
      - in: query
        name: filename
        schema:
            type: string
        required: true
        description: The name of the file.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getFileResponse'
    post:
      operationId: modifyFile
      summary: Modify a file
      parameters:
      - in: query
        name: filename
        schema:
            type: string
        required: true
        description: The name of the file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modifyFileRequest'
      responses:
        "200":
          description: OK
  /create_env:
    post:
      operationId: createEnv
      summary: Create a new Conda environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createEnvRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createEnvResponse'
        "400":
          description: Environment creation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createEnvErrorResponse'
  /run_script:
    post:
      operationId: runScript
      summary: Run a Python script in a Conda environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runScriptRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runScriptResponse'
        "400":
          description: Script execution failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runScriptErrorResponse'
components:
  schemas:
    getFileResponse:
      type: object
      properties:
        content:
          type: string
          description: The content of the file.
    modifyFileRequest:
      type: object
      required:
      - content
      properties:
        content:
          type: string
          description: The new content of the file.
    createEnvRequest:
      type: object
      required:
      - env_name
      properties:
        env_name:
          type: string
          description: The name of the new environment.
    createEnvResponse:
      type: object
      properties:
        output:
          type: string
          description: The output of the command.
    createEnvErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message.
        output:
          type: string
          description: The output of the command before it failed.
    runScriptRequest:
      type: object
      required:
      - env_name
      - script_path
      properties:
        env_name:
          type: string
          description: The name of the environment.
        script_path:
          type: string
          description: The path to the Python script.
    runScriptResponse:
      type: object
      properties:
        output:
          type: string
          description: The output of the script.
    runScriptErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message.
        output:
          type: string
          description: The output of the script before it failed.
