openapi: 3.0.1
info:
  title: Simple Plugin
  description: A simple plugin that processes input data.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /process:
    post:
      operationId: process
      summary: Process input data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
